import { RISK_AGGREGATION_STRATEGY_VERSION, RISK_ENGINE_VERSION } from '../../domain/constants';
import type { RiskRulePackDefinition } from '../../domain/rulePack';

/**
 * SYNTHETIC DEVELOPMENT PRIORITY RULE PACK — NOT CLINICAL GUIDANCE.
 * Uses non-clinical labels and artificial thresholds for engine testing only.
 * Never load in production.
 */
export const SYNTHETIC_DEV_PRIORITY_RULE_PACK: RiskRulePackDefinition = {
  rulePackId: 'synthetic-dev-priority-v1',
  title: 'Development priority rules (synthetic)',
  description:
    'Synthetic rules for deterministic engine tests. Not maternal, newborn, child, or nutrition guidance.',
  version: 1,
  engineCompatibilityVersion: RISK_ENGINE_VERSION,
  status: 'APPROVED_FOR_DEVELOPMENT',
  applicableScreeningTemplateIds: ['synthetic-dev-workflow-v1'],
  applicableScreeningTemplateVersions: [1],
  applicableClientCategories: ['pregnant', 'postnatal', 'newborn', 'childUnderFive'],
  applicableVisitTypes: [
    'antenatalVisit',
    'postnatalVisit',
    'newbornVisit',
    'childVisit',
    'followUp',
    'other',
  ],
  effectiveDate: null,
  retiredDate: null,
  sourceReferences: ['synthetic-dev-priority'],
  clinicalReview: {
    required: true,
    reviewedBy: null,
    reviewedAt: null,
  },
  developmentBanner: 'Development priority rules — not clinical guidance',
  aggregationStrategy: 'highestApprovedPriorityWins',
  aggregationStrategyVersion: RISK_AGGREGATION_STRATEGY_VERSION,
  completenessPolicy: {
    greenRequiresExplicitMatchedRule: true,
    greenRequiresNoBlockingMissingInformation: true,
    greenRequiresCompleteRequiredInputs: ['item_a1', 'item_a2', 'item_b1_weight'],
    blockingAnswerStates: ['unknown', 'notAssessed', 'declined', 'unanswered'],
  },
  explanationVersion: 'synthetic-dev-priority-explanations@1',
  knownQuestionKeys: [
    'item_a1',
    'item_a2',
    'item_a3_detail',
    'item_b1_weight',
    'item_b2',
    'item_b3_ack',
    'item_c1',
    'item_c2',
  ],
  rules: [
    {
      ruleId: 'syn-red-example-condition-a',
      title: 'Example condition A',
      priority: 'red',
      description: 'Synthetic RED path when assessment item A1 is Yes.',
      order: 10,
      enabled: true,
      condition: {
        op: 'equals',
        questionKey: 'item_a1',
        value: true,
      },
      requiredInputs: ['item_a1'],
      explanation: {
        explanationId: 'syn-exp-red-a',
        version: 1,
        summary: 'Example condition A was recorded as Yes',
        detail:
          'Development rule matched Example condition A. This is not a diagnosis or clinical danger-sign finding.',
        reviewStatus: 'APPROVED_FOR_DEVELOPMENT',
        sourceReferences: ['synthetic-dev-priority'],
      },
      workerActionText: 'Review the recorded information and continue when ready',
      sourceReferences: ['synthetic-dev-priority'],
      contentReviewStatus: 'APPROVED_FOR_DEVELOPMENT',
      effectiveDate: null,
      retiredDate: null,
    },
    {
      ruleId: 'syn-amber-example-observation-b',
      title: 'Example observation B',
      priority: 'amber',
      description: 'Synthetic AMBER path when assessment item A2 is option two.',
      order: 20,
      enabled: true,
      condition: {
        op: 'equals',
        questionKey: 'item_a2',
        value: 'option_two',
      },
      requiredInputs: ['item_a2'],
      explanation: {
        explanationId: 'syn-exp-amber-b',
        version: 1,
        summary: 'Example observation B was recorded as option two',
        detail:
          'Development rule matched Example observation B. This is not clinical follow-up guidance.',
        reviewStatus: 'APPROVED_FOR_DEVELOPMENT',
        sourceReferences: ['synthetic-dev-priority'],
      },
      workerActionText: 'Review contributing factors before continuing',
      sourceReferences: ['synthetic-dev-priority'],
      contentReviewStatus: 'APPROVED_FOR_DEVELOPMENT',
      effectiveDate: null,
      retiredDate: null,
    },
    {
      ruleId: 'syn-amber-compound-example',
      title: 'Example compound observation',
      priority: 'amber',
      description: 'Synthetic compound rule for all/any testing.',
      order: 25,
      enabled: true,
      condition: {
        op: 'all',
        conditions: [
          {
            op: 'in',
            questionKey: 'item_a2',
            values: ['option_three'],
          },
          {
            op: 'greaterThanOrEqual',
            questionKey: 'item_b2',
            value: 5,
          },
        ],
      },
      requiredInputs: ['item_a2', 'item_b2'],
      explanation: {
        explanationId: 'syn-exp-amber-compound',
        version: 1,
        summary: 'Example compound observation matched',
        detail:
          'Development compound rule matched. Artificial thresholds only — not clinical criteria.',
        reviewStatus: 'APPROVED_FOR_DEVELOPMENT',
        sourceReferences: ['synthetic-dev-priority'],
      },
      workerActionText: 'Review the matched example factors',
      sourceReferences: ['synthetic-dev-priority'],
      contentReviewStatus: 'APPROVED_FOR_DEVELOPMENT',
      effectiveDate: null,
      retiredDate: null,
    },
    {
      ruleId: 'syn-red-measurement-c',
      title: 'Example measurement C',
      priority: 'red',
      description: 'Synthetic RED when measurement B1 is outside an artificial range.',
      order: 15,
      enabled: true,
      condition: {
        op: 'outsideRange',
        questionKey: 'item_b1_weight',
        min: 1,
        max: 200,
        measurementUnit: 'kg',
      },
      requiredInputs: ['item_b1_weight'],
      explanation: {
        explanationId: 'syn-exp-red-measurement-c',
        version: 1,
        summary: 'Example measurement C was outside the development test range',
        detail:
          'Development measurement rule matched. The numeric bounds are artificial and not clinical thresholds.',
        reviewStatus: 'APPROVED_FOR_DEVELOPMENT',
        sourceReferences: ['synthetic-dev-priority'],
      },
      workerActionText: 'Review the recorded measurement entry',
      sourceReferences: ['synthetic-dev-priority'],
      contentReviewStatus: 'APPROVED_FOR_DEVELOPMENT',
      effectiveDate: null,
      retiredDate: null,
    },
    {
      ruleId: 'syn-green-routine-example',
      title: 'Example routine pattern',
      priority: 'green',
      description:
        'Synthetic GREEN only when explicit routine pattern matches and required inputs are complete.',
      order: 100,
      enabled: true,
      condition: {
        op: 'all',
        conditions: [
          { op: 'equals', questionKey: 'item_a1', value: false },
          { op: 'equals', questionKey: 'item_a2', value: 'option_one' },
          {
            op: 'between',
            questionKey: 'item_b1_weight',
            min: 1,
            max: 200,
            measurementUnit: 'kg',
          },
          { op: 'not', condition: { op: 'isMissing', questionKey: 'item_b3_ack' } },
        ],
      },
      requiredInputs: ['item_a1', 'item_a2', 'item_b1_weight', 'item_b3_ack'],
      explanation: {
        explanationId: 'syn-exp-green-routine',
        version: 1,
        summary: 'Example routine pattern matched for development testing',
        detail:
          'Development green rule matched an explicit routine pattern. This does not mean the client is healthy, safe, or free of clinical risk.',
        reviewStatus: 'APPROVED_FOR_DEVELOPMENT',
        sourceReferences: ['synthetic-dev-priority'],
      },
      workerActionText: 'Continue with routine monitoring workflow wording only',
      sourceReferences: ['synthetic-dev-priority'],
      contentReviewStatus: 'APPROVED_FOR_DEVELOPMENT',
      effectiveDate: null,
      retiredDate: null,
    },
  ],
};
