import type { KnowledgePackDefinition } from '../../domain/types';
import { computePackChecksum } from '../validation/validatePack';

const DEVELOPMENT_BANNER =
  'Development Ask NorthCare content — not clinical guidance';

const SYNTHETIC_SOURCE = {
  sourceId: 'synthetic-dev-source-a',
  title: 'Synthetic Development Reference Pack Notes — Example Care Topic A (Long Title For Wrapping Tests)',
  issuingOrganisation: null,
  versionOrYear: '2026-dev',
  section: 'Example section A',
  usageNote: 'Synthetic development fixture only. Not issued by WHO, UNICEF, GHS or any clinical body.',
} as const;

const PACK_WITHOUT_CHECKSUM: Omit<KnowledgePackDefinition, 'contentChecksum'> = {
  knowledgePackId: 'synthetic-dev-ask-northcare-v1',
  title: 'Synthetic Development Ask NorthCare Pack',
  description:
    'Clearly synthetic development-only knowledge for retrieval, safety routing and UI tests. Not clinical guidance.',
  version: 1,
  status: 'APPROVED_FOR_DEVELOPMENT',
  jurisdiction: null,
  issuingOrganisation: null,
  sourceReferences: [SYNTHETIC_SOURCE],
  applicableRoles: ['worker'],
  applicableTopics: [
    'topic-example-care-a',
    'topic-example-workflow-b',
    'topic-development-reference-c',
    'topic-app-help-offline',
  ],
  supportedLanguages: ['en'],
  effectiveDate: null,
  retiredDate: null,
  reviewedBy: null,
  reviewedAt: null,
  implementationPath:
    'apps/mobile/src/features/assistant/content/packs/syntheticDevAskNorthCarePack.ts',
  knownLimitations: [
    'Synthetic content only',
    'No clinical approval',
    'Not for production',
    'No Dagbanli content',
  ],
  developmentBanner: DEVELOPMENT_BANNER,
  family: 'syntheticDevelopment',
  topics: [
    {
      topicId: 'topic-example-care-a',
      title: 'Example care topic A',
      description: 'Synthetic general care reference for development tests.',
      status: 'APPROVED_FOR_DEVELOPMENT',
      applicableKnowledgePacks: ['synthetic-dev-ask-northcare-v1'],
      applicableRole: 'worker',
      clinicalReviewStatus: 'notReviewed',
      supportedLanguages: ['en'],
      icon: 'care',
      order: 1,
      family: 'syntheticDevelopment',
    },
    {
      topicId: 'topic-example-workflow-b',
      title: 'Example workflow topic B',
      description: 'Synthetic workflow reference for development tests.',
      status: 'APPROVED_FOR_DEVELOPMENT',
      applicableKnowledgePacks: ['synthetic-dev-ask-northcare-v1'],
      applicableRole: 'worker',
      clinicalReviewStatus: 'notReviewed',
      supportedLanguages: ['en'],
      icon: 'workflow',
      order: 2,
      family: 'syntheticDevelopment',
    },
    {
      topicId: 'topic-development-reference-c',
      title: 'Development reference C',
      description: 'Synthetic multi-source and long-answer reference.',
      status: 'APPROVED_FOR_DEVELOPMENT',
      applicableKnowledgePacks: ['synthetic-dev-ask-northcare-v1'],
      applicableRole: 'worker',
      clinicalReviewStatus: 'notReviewed',
      supportedLanguages: ['en'],
      icon: 'reference',
      order: 3,
      family: 'syntheticDevelopment',
    },
    {
      topicId: 'topic-app-help-offline',
      title: 'Offline application help',
      description: 'How to use NorthCare AI features that are already implemented.',
      status: 'APPROVED_FOR_DEVELOPMENT',
      applicableKnowledgePacks: ['synthetic-dev-ask-northcare-v1'],
      applicableRole: 'worker',
      clinicalReviewStatus: 'notReviewed',
      supportedLanguages: ['en'],
      icon: 'help',
      order: 4,
      family: 'offlineApplicationHelp',
    },
  ],
  articles: [
    {
      articleId: 'article-example-care-a-exact',
      packId: 'synthetic-dev-ask-northcare-v1',
      title: 'Example care topic A — approved overview',
      shortTitle: 'Care topic A overview',
      topicId: 'topic-example-care-a',
      summary: 'Synthetic approved overview for exact-match retrieval tests.',
      approvedAnswer: [
        {
          kind: 'paragraph',
          text: 'This is synthetic approved reference text for Example care topic A. It is not clinical guidance.',
        },
        {
          kind: 'bullet',
          text: 'Use this content only to verify Ask NorthCare retrieval behaviour.',
        },
        {
          kind: 'safetyNote',
          text: 'Ask NorthCare does not diagnose or replace clinical judgement.',
        },
      ],
      sections: [
        {
          sectionId: 'section-overview',
          heading: 'Overview',
          blocks: [
            {
              kind: 'paragraph',
              text: 'Synthetic section content for the article screen.',
            },
          ],
        },
      ],
      keywords: ['example', 'care', 'topic', 'overview'],
      alternativePhrases: ['tell me about example care topic a'],
      approvedQuestionPatterns: [
        'what is example care topic a',
        'explain example care topic a',
      ],
      sourceReferences: [SYNTHETIC_SOURCE],
      audience: 'worker',
      jurisdiction: null,
      language: 'en',
      version: 1,
      status: 'APPROVED_FOR_DEVELOPMENT',
      effectiveDate: null,
      retiredDate: null,
      relatedArticleIds: ['article-example-care-a-keyword'],
      workflowLinks: [
        {
          linkId: 'link-clients',
          label: 'Open Clients',
          route: '/(worker)/clients',
        },
      ],
      safetyNote: 'Synthetic development content — not clinical guidance.',
      isClinical: false,
    },
    {
      articleId: 'article-example-care-a-keyword',
      packId: 'synthetic-dev-ask-northcare-v1',
      title: 'Example care topic A — keyword notes',
      shortTitle: 'Care topic A keywords',
      topicId: 'topic-example-care-a',
      summary: 'Synthetic keyword-match article.',
      approvedAnswer: [
        {
          kind: 'paragraph',
          text: 'Synthetic keyword notes for Example care topic A used during development search tests.',
        },
      ],
      sections: [],
      keywords: ['hydration', 'rest', 'follow-up', 'example'],
      alternativePhrases: ['example care keyword notes'],
      approvedQuestionPatterns: [],
      sourceReferences: [SYNTHETIC_SOURCE],
      audience: 'worker',
      jurisdiction: null,
      language: 'en',
      version: 1,
      status: 'APPROVED_FOR_DEVELOPMENT',
      effectiveDate: null,
      retiredDate: null,
      relatedArticleIds: ['article-example-care-a-exact'],
      workflowLinks: [],
      safetyNote: null,
      isClinical: false,
    },
    {
      articleId: 'article-workflow-b',
      packId: 'synthetic-dev-ask-northcare-v1',
      title: 'Example workflow topic B — draft saving',
      shortTitle: 'Workflow B drafts',
      topicId: 'topic-example-workflow-b',
      summary: 'Synthetic workflow help for saving drafts.',
      approvedAnswer: [
        {
          kind: 'paragraph',
          text: 'In development, draft records stay on this device until an approved sync path exists.',
        },
        {
          kind: 'bullet',
          text: 'Open the relevant workflow and continue the draft from the client profile.',
        },
      ],
      sections: [],
      keywords: ['draft', 'save', 'workflow', 'example'],
      alternativePhrases: ['how to save a draft in example workflow b'],
      approvedQuestionPatterns: ['how to save a draft'],
      sourceReferences: [
        {
          sourceId: 'synthetic-dev-source-b',
          title: 'Synthetic Product Help Notes',
          issuingOrganisation: null,
          versionOrYear: '2026-dev',
          section: 'Drafts',
          usageNote: 'Synthetic product-help fixture.',
        },
      ],
      audience: 'worker',
      jurisdiction: null,
      language: 'en',
      version: 1,
      status: 'APPROVED_FOR_DEVELOPMENT',
      effectiveDate: null,
      retiredDate: null,
      relatedArticleIds: [],
      workflowLinks: [
        {
          linkId: 'link-home',
          label: 'Return to worker home',
          route: '/(worker)',
        },
      ],
      safetyNote: null,
      isClinical: false,
    },
    {
      articleId: 'article-reference-c-long',
      packId: 'synthetic-dev-ask-northcare-v1',
      title: 'Development reference C — long answer',
      shortTitle: 'Reference C long',
      topicId: 'topic-development-reference-c',
      summary: 'Long synthetic answer for layout testing.',
      approvedAnswer: [
        {
          kind: 'paragraph',
          text: 'This long synthetic answer exists to verify scrolling, large text, and multi-paragraph layout. It repeats approved fixture wording without adding clinical facts.',
        },
        {
          kind: 'paragraph',
          text: 'Paragraph two continues the synthetic reference. Workers should never treat this as guidance for real care decisions.',
        },
        {
          kind: 'paragraph',
          text: 'Paragraph three confirms that Ask NorthCare answers must remain source-backed and versioned even when content is long.',
        },
        {
          kind: 'bullet',
          text: 'Synthetic step one: open Ask NorthCare.',
        },
        {
          kind: 'bullet',
          text: 'Synthetic step two: review the scope and privacy reminder.',
        },
        {
          kind: 'bullet',
          text: 'Synthetic step three: ask a general question using approved topics.',
        },
      ],
      sections: [
        {
          sectionId: 'section-long',
          heading: 'Extended synthetic notes',
          blocks: [
            {
              kind: 'paragraph',
              text: 'Additional synthetic section content for article reading.',
            },
          ],
        },
      ],
      keywords: ['development', 'reference', 'long', 'answer'],
      alternativePhrases: ['show me the long development reference'],
      approvedQuestionPatterns: ['show long development reference c'],
      sourceReferences: [SYNTHETIC_SOURCE],
      audience: 'worker',
      jurisdiction: null,
      language: 'en',
      version: 1,
      status: 'APPROVED_FOR_DEVELOPMENT',
      effectiveDate: null,
      retiredDate: null,
      relatedArticleIds: ['article-reference-c-alt'],
      workflowLinks: [],
      safetyNote: 'Development Ask NorthCare content — not clinical guidance',
      isClinical: false,
    },
    {
      articleId: 'article-reference-c-alt',
      packId: 'synthetic-dev-ask-northcare-v1',
      title: 'Development reference C — alternate source',
      shortTitle: 'Reference C alternate',
      topicId: 'topic-development-reference-c',
      summary: 'Second synthetic source for multi-citation tests.',
      approvedAnswer: [
        {
          kind: 'paragraph',
          text: 'Alternate synthetic source card for multipleRelevantSources ranking tests.',
        },
      ],
      sections: [],
      keywords: ['development', 'reference', 'long', 'answer', 'alternate'],
      alternativePhrases: ['alternate development reference c'],
      approvedQuestionPatterns: ['show long development reference c'],
      sourceReferences: [
        {
          sourceId: 'synthetic-dev-source-c',
          title: 'Another Synthetic Development Source With An Especially Long Title For Wrapping',
          issuingOrganisation: null,
          versionOrYear: '2026-dev',
          section: 'Alternate',
          usageNote: 'Synthetic fixture.',
        },
      ],
      audience: 'worker',
      jurisdiction: null,
      language: 'en',
      version: 1,
      status: 'APPROVED_FOR_DEVELOPMENT',
      effectiveDate: null,
      retiredDate: null,
      relatedArticleIds: ['article-reference-c-long'],
      workflowLinks: [],
      safetyNote: null,
      isClinical: false,
    },
    {
      articleId: 'article-app-help-lock',
      packId: 'synthetic-dev-ask-northcare-v1',
      title: 'How to lock the application',
      shortTitle: 'Lock the app',
      topicId: 'topic-app-help-offline',
      summary: 'Product-help answer reflecting implemented lock behaviour.',
      approvedAnswer: [
        {
          kind: 'paragraph',
          text: 'From the worker home screen, choose Lock. The session becomes locked and Ask NorthCare conversation content is cleared according to policy.',
        },
      ],
      sections: [],
      keywords: ['lock', 'application', 'session', 'security'],
      alternativePhrases: ['how do i lock the app'],
      approvedQuestionPatterns: ['how to lock the application'],
      sourceReferences: [
        {
          sourceId: 'synthetic-dev-source-help',
          title: 'Synthetic NorthCare Product Help',
          issuingOrganisation: null,
          versionOrYear: '2026-dev',
          section: 'Lock',
          usageNote: 'Reflects implemented behaviour only.',
        },
      ],
      audience: 'worker',
      jurisdiction: null,
      language: 'en',
      version: 1,
      status: 'APPROVED_FOR_DEVELOPMENT',
      effectiveDate: null,
      retiredDate: null,
      relatedArticleIds: [],
      workflowLinks: [
        {
          linkId: 'link-home-lock',
          label: 'Return to worker home',
          route: '/(worker)',
        },
      ],
      safetyNote: null,
      isClinical: false,
    },
    {
      articleId: 'article-retired-example',
      packId: 'synthetic-dev-ask-northcare-v1',
      title: 'Retired synthetic article',
      shortTitle: 'Retired article',
      topicId: 'topic-example-care-a',
      summary: 'Retired fixture — must not answer new questions.',
      approvedAnswer: [
        {
          kind: 'paragraph',
          text: 'This retired synthetic article must not be used for new answers.',
        },
      ],
      sections: [],
      keywords: ['retired', 'obsolete'],
      alternativePhrases: [],
      approvedQuestionPatterns: ['retired synthetic article question'],
      sourceReferences: [SYNTHETIC_SOURCE],
      audience: 'worker',
      jurisdiction: null,
      language: 'en',
      version: 1,
      status: 'RETIRED',
      effectiveDate: null,
      retiredDate: '2026-01-01',
      relatedArticleIds: [],
      workflowLinks: [],
      safetyNote: 'Content is no longer active.',
      isClinical: false,
    },
  ],
};

export const SYNTHETIC_DEV_ASK_NORTHCARE_PACK: KnowledgePackDefinition = {
  ...PACK_WITHOUT_CHECKSUM,
  contentChecksum: computePackChecksum({
    ...PACK_WITHOUT_CHECKSUM,
    contentChecksum: '',
  }),
};
